<a href="https://colab.research.google.com/github/falawar7/AAI614_ELAWAR/blob/main/Week3/Data_Scraping_FluWatch_Faisal_Elawar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Practical Exercise: Data Scraping**

[FluWatch](https://www.canada.ca/en/public-health/services/diseases/flu-influenza/influenza-surveillance.html) is Canada's national surveillance system that monitors the spread of flu and flu-like illnesses. Write a Python program to scrape the data in [Table 2](https://www.canada.ca/en/public-health/services/surveillance/respiratory-virus-detections-canada/2018-2019/respiratory-virus-detections-isolations-week-01-ending-january-5-2019.html) into a pandas DataFrame

https://www.canada.ca/en/public-health/services/surveillance/respiratory-virus-detections-canada/2018-2019/respiratory-virus-detections-isolations-week-01-ending-january-5-2019.html

In [35]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import re
import pandas as pd

html = urlopen('https://www.canada.ca/en/public-health/services/surveillance/respiratory-virus-detections-canada/2018-2019/respiratory-virus-detections-isolations-week-01-ending-january-5-2019.html')
bs = BeautifulSoup(html, 'html.parser')

table = bs.find('table')

headers = []
for header in table.find_all('th'):
    headers.append(header.text)

data = []
for row in table.find_all('tr'):
    row_data = []
    for cell in row.find_all('td'):
        row_data.append(cell.text)
    data.append(row_data)

table2= pd.DataFrame(data, columns = headers)
table2.head()

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,Newfoundland,171,0,0,34,34,0,171,25,171,...,0,0,171,0,171,4,171,21,N.A.,N.A.
2,Prince Edward Island,46,17,0,0,17,0,47,4,0,...,0,0,0,0,0,0,0,0,0,0
3,Nova Scotia,138,0,0,20,20,1,139,12,11,...,0,0,11,0,11,0,11,1,11,0
4,New Brunswick,875,0,0,211,211,0,875,33,129,...,2,0,129,5,129,2,129,7,129,3

In [17]:
table2.shape

(43, 23)

In [18]:
table2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Reporting Laboratory   42 non-null     object
 1   Flu Tested             41 non-null     object
 2   A(H1N1)pdm09 Positive  41 non-null     object
 3   A(H3) Positive         41 non-null     object
 4   A(UnS) Positive        41 non-null     object
 5   Total Flu A Positive   41 non-null     object
 6   Total Flu B Positive   41 non-null     object
 7   RSV Tested             41 non-null     object
 8   RSV Positive           41 non-null     object
 9   PIV Tested             41 non-null     object
 10  PIV 1 Positive         41 non-null     object
 11  PIV 2 Positive         41 non-null     object
 12  PIV 3 Positive         41 non-null     object
 13  PIV 4 Positive         41 non-null     object
 14  Other PIV Positive     41 non-null     object
 15  Adeno Tested           41 non-null     object
 16  Adeno Positive         41 non-null     object
 17  hMPV Tested            41 non-null     object
 18  hMPV Positive          41 non-null     object
 19  Entero/Rhino Tested    41 non-null     object
 20  Entero/Rhino Positive  41 non-null     object
 21  Coron Tested           41 non-null     object
 22  Coron Positive         41 non-null     object
dtypes: object(23)
memory usage: 7.9+ KB

# **Cleaning the Table**

In [36]:
table2 = table2.drop(0)

In [37]:
table2.head()

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
1,Newfoundland,171,0,0,34,34,0,171,25,171,...,0,0,171,0,171,4,171,21,N.A.,N.A.
2,Prince Edward Island,46,17,0,0,17,0,47,4,0,...,0,0,0,0,0,0,0,0,0,0
3,Nova Scotia,138,0,0,20,20,1,139,12,11,...,0,0,11,0,11,0,11,1,11,0
4,New Brunswick,875,0,0,211,211,0,875,33,129,...,2,0,129,5,129,2,129,7,129,3
5,Atlantic,1230,17,0,265,282,1,1232,74,311,...,2,0,311,5,311,6,311,29,140,3

In [42]:
table2.iloc[40:]

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
41,CANADA,13452,847,55,2494,3396,28,12661,1180,4247,...,22,0,4237,36,4174,86,2705,300,3074,142
42,"Specimens from Yukon (YT), Northwest Territori...",None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [43]:
table2 = table2.drop(42)

In [45]:
table2.head()

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
1,Newfoundland,171,0,0,34,34,0,171,25,171,...,0,0,171,0,171,4,171,21,N.A.,N.A.
2,Prince Edward Island,46,17,0,0,17,0,47,4,0,...,0,0,0,0,0,0,0,0,0,0
3,Nova Scotia,138,0,0,20,20,1,139,12,11,...,0,0,11,0,11,0,11,1,11,0
4,New Brunswick,875,0,0,211,211,0,875,33,129,...,2,0,129,5,129,2,129,7,129,3
5,Atlantic,1230,17,0,265,282,1,1232,74,311,...,2,0,311,5,311,6,311,29,140,3

In [46]:
table2.iloc[40:]

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
41,CANADA,13452,847,55,2494,3396,28,12661,1180,4247,...,22,0,4237,36,4174,86,2705,300,3074,142

In [47]:
table2.shape

(41, 23)

# **Saving to CSV**

In [48]:
table2.to_csv('Respiratory Virus Report, Week 01 ending January 5, 2019.csv', index=False)

In [52]:
exported_table = pd.read_csv('/content/Respiratory Virus Report, Week 01 ending January 5, 2019.csv')

In [54]:
exported_table.shape

(41, 23)

In [55]:
exported_table

,Reporting Laboratory,Flu Tested,A(H1N1)pdm09 Positive,A(H3) Positive,A(UnS) Positive,Total Flu A Positive,Total Flu B Positive,RSV Tested,RSV Positive,PIV Tested,...,PIV 4 Positive,Other PIV Positive,Adeno Tested,Adeno Positive,hMPV Tested,hMPV Positive,Entero/Rhino Tested,Entero/Rhino Positive,Coron Tested,Coron Positive
0,Newfoundland,171,0,0,34,34,0,171,25,171,...,0,0,171,0,171,4,171,21,N.A.,N.A.
1,Prince Edward Island,46,17,0,0,17,0,47,4,0,...,0,0,0,0,0,0,0,0,0,0
2,Nova Scotia,138,0,0,20,20,1,139,12,11,...,0,0,11,0,11,0,11,1,11,0
3,New Brunswick,875,0,0,211,211,0,875,33,129,...,2,0,129,5,129,2,129,7,129,3
4,Atlantic,1230,17,0,265,282,1,1232,74,311,...,2,0,311,5,311,6,311,29,140,3
5,Région Nord-Est,441,0,0,104,104,1,335,14,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
6,Québec-Chaudière-Appalaches,1054,0,0,300,300,1,1091,133,85,...,0,0,85,4,62,0,N.A.,N.A.,62,0
7,Centre-du-Québec,1394,0,0,438,438,11,1139,113,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
8,Montréal-Laval,1724,0,0,380,380,3,1582,186,530,...,1,0,530,9,516,13,N.A.,N.A.,516,40
9,Ouest du Québec,1013,0,0,253,253,1,976,156,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
10,Montérégie,627,0,0,152,152,0,627,44,0,...,0,0,0,0,0,0,N.A.,N.A.,0,0
11,Province of Québec,6253,0,0,1627,1627,17,5750,646,615,...,1,0,615,13,578,13,N.A.,N.A.,578,40
12,Ottawa P.H.L.,64,11,1,3,15,0,64,12,19,...,0,0,19,0,17,0,2,0,0,0
13,CHEO - Ottawa,363,0,0,52,52,0,363,80,27,...,2,0,27,0,27,2,18,6,26,4
14,Kingston P.H.L.,50,11,0,0,11,0,50,5,18,...,0,0,18,0,18,0,0,0,0,0
15,UHN / Mount Sinai Hospital,496,0,0,66,66,2,496,47,10,...,0,0,0,0,10,0,N.A.,N.A.,N.A.,N.A.
16,P.H.O.L. - Toronto,696,114,24,9,147,0,646,54,445,...,0,0,445,2,441,3,4,0,0,0
17,Sick Kids Hospital - Toronto,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,Sunnybrook & Women's College HSC,106,17,4,1,22,0,106,5,106,...,0,0,106,0,106,1,106,6,106,2
19,Sault Ste. Marie P.H.L.,12,1,1,0,2,0,10,0,10,...,0,0,10,0,9,0,1,0,0,0
20,Timmins P.H.L.,18,7,0,0,7,0,11,0,11,...,0,0,11,0,11,0,0,0,0,0
21,St. Joseph's - London,230,0,0,25,25,0,230,41,66,...,2,0,66,1,66,2,21,3,21,1
22,London P.H.L.,181,24,2,2,28,0,180,22,128,...,0,0,128,0,124,0,4,0,0,0
23,Orillia P.H.L.,45,4,0,2,6,0,45,6,12,...,0,0,12,0,12,0,0,0,0,0
24,Thunder Bay P.H.L.,20,6,0,1,7,0,19,1,11,...,0,0,11,0,11,0,0,0,0,0
25,Sudbury P.H.L.,44,3,0,0,3,0,41,2,40,...,0,0,40,0,40,2,0,0,0,0
26,Hamilton P.H.L.,148,28,3,1,32,0,147,14,89,...,0,0,89,1,88,0,1,0,0,0
27,Peterborough P.H.L.,73,16,1,5,22,0,73,15,14,...,0,0,14,0,13,0,1,0,0,0
28,Province of Ontario,2546,242,36,167,445,2,2481,304,1006,...,4,0,996,4,993,10,168,15,153,7
29,Manitoba,455,13,0,108,121,1,455,28,95,...,0,0,95,2,72,1,95,8,72,3
30,Regina,572,188,5,21,214,1,572,27,572,...,4,0,572,4,572,7,572,60,572,10
31,Saskatoon,215,0,0,54,54,2,215,31,215,...,2,0,215,0,215,3,215,7,215,0
32,Province of Saskatchewan,787,188,5,75,268,3,787,58,787,...,6,0,787,4,787,10,787,67,787,10
33,Province of Alberta,1279,178,5,43,226,3,1076,0,1076,...,6,0,1076,5,1076,41,1076,132,1076,64
34,Prairies,2521,379,10,226,615,7,2318,86,1958,...,12,0,1958,11,1935,52,1958,207,1935,77
35,British Columbia,861,192,8,207,407,1,861,70,338,...,3,0,338,3,338,5,249,45,249,15
36,Yukon,21,11,1,2,14,0,0,0,N.A.,...,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.,N.A.
37,Northwest Territories,19,5,0,0,5,0,18,0,18,...,0,0,18,0,18,0,18,3,18,0
38,Nunavut,1,1,0,0,1,0,1,0,1,...,0,0,1,0,1,0,1,1,1,0
39,Territories,41,17,1,2,20,0,19,0,19,...,0,0,19,0,19,0,19,4,19,0
40,CANADA,13452,847,55,2494,3396,28,12661,1180,4247,...,22,0,4237,36,4174,86,2705,300,3074,142